name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: 0 0 * * *

jobs:
  stable:
    name: Deno Stable
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        deno: [v1.x]
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Run tests
        run: deno test --coverage=./cov --allow-all --unstable --jobs 2

      - name: Generate lcov
        run: deno coverage --unstable --lcov ./cov > cov.lcov

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.deno }}
          files: cov.lcov
